// database.types.ts is generated by `supabase gen types typescript` — do not
// hand-edit it. Regenerate after every schema migration:
//   pnpm --filter @audio-tool/shared-types gen-types
export type { Database, Json } from "./database.types.js";
import type { Database } from "./database.types.js";

type Tables = Database["public"]["Tables"];

export type Profile = Tables["profiles"]["Row"];
export type ProfileInsert = Tables["profiles"]["Insert"];

export type AudioFile = Tables["audio_files"]["Row"];
export type AudioFileInsert = Tables["audio_files"]["Insert"];
export type AudioFileUpdate = Tables["audio_files"]["Update"];

// Annotation carries `version` for optimistic concurrency — see AGENTS.md
// "Key technical decisions". Always send `.eq('version', clientVersion)`
// when updating; 0 rows affected means a stale write, surface as a conflict.
export type Annotation = Tables["annotations"]["Row"];
export type AnnotationInsert = Tables["annotations"]["Insert"];
export type AnnotationUpdate = Tables["annotations"]["Update"];

export type ExtractionJobStatus =
  | "pending"
  | "processing"
  | "completed"
  | "failed";

export type ExtractionJob = Tables["extraction_jobs"]["Row"];
export type ExtractionJobInsert = Tables["extraction_jobs"]["Insert"];
export type ExtractionJobUpdate = Tables["extraction_jobs"]["Update"];
